version: '3'

services:
  sql-server:
    build:
      context: ./windowsServerWithSQL
    ports:
      - "1433:1433"
    environment:
      sa_password: Bintu123
      ACCEPT_EULA: Y
      attach_dbs: '[{"dbName":"SampleDB","dbFiles":["C:\\temp\\sampledb.mdf","C:\\temp\\sampledb_log.ldf"]}]'

  web-app:
    build:
      context: ./windowsServerWithDotNet
    ports:
      - "80:80"
    depends_on:
      - sql-server
